/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.lab;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest2 {
    @Test
    void test2() throws Exception {
        Thread.sleep(1000);
        assertTrue(true);
    }

}
